name: pumptrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  fluentui_system_icons: ^1.1.255
  wave: ^0.2.2
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1
  google_maps_flutter: ^2.6.1
  firebase_core: ^3.4.0
  location: ^6.0.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
