// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '#',
    appId: '1:305208815775:web:46895c54c56e794b8c72aa',
    messagingSenderId: '305208815775',
    projectId: 'pumptrack-c857a',
    authDomain: 'pumptrack-c857a.firebaseapp.com',
    storageBucket: 'pumptrack-c857a.appspot.com',
    measurementId: 'G-BTHNR4LBH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '#',
    appId: '1:305208815775:android:0c3118b3c50847838c72aa',
    messagingSenderId: '305208815775',
    projectId: 'pumptrack-c857a',
    storageBucket: 'pumptrack-c857a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '#',
    appId: '1:305208815775:ios:4b591c7a945292608c72aa',
    messagingSenderId: '305208815775',
    projectId: 'pumptrack-c857a',
    storageBucket: 'pumptrack-c857a.appspot.com',
    iosBundleId: 'com.example.pumptrack',
  );
}
